name: Update tags and docs for new release
on:
  release:
    types: [published]

jobs:
  tag:
    name: Add/update 'latest' tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Update docs
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs

      - name: Deploy documentation
        uses: dbots-pkg/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
