name: TS definitions
on:
  push:
    branches:
      - "*"
      - "!docs"
    paths:
      - "src/**"
      - "typings/**"
      - package.json
      - scripts/post-types.js
      - ".github/workflows/typings.yml"

jobs:
  types:
    name: Update TS definitions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Generate typings
        run: npm run types

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: typings
          message: "[auto] Update typings"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
